import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";

export default function Home() {
  const { data, error } = useSWR("/api/jokes", fetcher);

  if (error) return <div>failed to load</div>;
  if (!data) {
    return <div>loading</div>;
  }

  //console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>API Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jokes</h1>
        <ul>
          {data.map((joke) => {
            return (
              <li key={joke.id}>
                {joke.text}
                <br></br>
                <p>{joke.author}</p>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );

  function fetcher(url) {
    if (!url) return;

    return fetch(url).then((res) => res.json());
  }
}
